version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${STORAGE_DIR}:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
volumes:
  dbdata:
